import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    "",
    {
      text: "Java基础",
      icon: "laptop-code",
      prefix: "JavaBase/",
      link:"JavaBase/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "JavaIO",
      icon: "laptop-code",
      prefix: "JavaIO/",
      link:"JavaIO/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Java反射",
      icon: "laptop-code",
      prefix: "JavaReflect/",
      link:"JavaReflect/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Java集合",
      icon: "laptop-code",
      prefix: "Java集合/",
      link:"Java集合/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Java多线程",
      icon: "laptop-code",
      prefix: "Java多线程/",
      link:"Java多线程/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "锁机制",
      icon: "laptop-code",
      prefix: "demo/",
      link:"demo/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "JUC包",
      icon: "laptop-code",
      prefix: "demo/",
      link:"demo/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "JavaWeb",
      icon: "laptop-code",
      prefix: "demo/",
      link:"demo/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Java框架",
      icon: "laptop-code",
      prefix: "demo/",
      link:"demo/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "设计模式",
      icon: "laptop-code",
      prefix: "demo/",
      link:"demo/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "计算机网络",
      icon: "laptop-code",
      prefix: "demo/",
      link:"demo/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "计算机网络",
      icon: "laptop-code",
      prefix: "demo/",
      link:"demo/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "数据库",
      icon: "laptop-code",
      prefix: "demo/",
      link:"demo/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "操作系统",
      icon: "laptop-code",
      prefix: "demo/",
      link:"demo/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Linux命令",
      icon: "laptop-code",
      prefix: "demo/",
      link:"demo/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "git",
      icon: "laptop-code",
      prefix: "demo/",
      link:"demo/",
      collapsible: true,
      children: "structure",
    },
    "slides",
    "guide/",
  
  ],
});
