import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/": [
    "",
    {
      text: "Java基础",
      icon: "laptop-code",
      prefix: "JavaBase/",
      link: "JavaBase/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "JavaIO",
      icon: "laptop-code",
      prefix: "JavaIO/",
      link: "JavaIO/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Java反射",
      icon: "laptop-code",
      prefix: "JavaReflect/",
      link: "JavaReflect/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Java集合",
      icon: "laptop-code",
      prefix: "Java集合/",
      link: "Java集合/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Java多线程",
      icon: "laptop-code",
      prefix: "Java多线程/",
      link: "Java多线程/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "锁机制",
      icon: "laptop-code",
      prefix: "demo/",
      link: "demo/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "JavaWeb",
      icon: "laptop-code",
      prefix: "javaWeb/",
      link: "javaWeb/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Java框架",
      icon: "laptop-code",
      prefix: "java框架/",
      link: "java框架/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "设计模式",
      icon: "laptop-code",
      prefix: "设计模式/",
      link: "设计模式/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "算法",
      icon: "laptop-code",
      prefix: "算法/",
      link: "算法/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "JVM",
      icon: "laptop-code",
      prefix: "JVM/",
      link: "JVM/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "海量数据",
      icon: "laptop-code",
      prefix: "海量数据/",
      link: "海量数据/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "计算机网络",
      icon: "laptop-code",
      prefix: "计算机网络/",
      link: "计算机网络/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "数据库",
      icon: "laptop-code",
      prefix: "数据库/",
      link: "数据库/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "Linux命令",
      icon: "laptop-code",
      prefix: "Linux命令/",
      link: "Linux命令/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "操作系统",
      icon: "laptop-code",
      prefix: "操作系统/",
      link: "操作系统/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "git",
      icon: "laptop-code",
      prefix: "git/",
      link: "git/",
      collapsible: true,
      children: "structure",
    },
    {
      text: "安全加密",
      icon: "laptop-code",
      prefix: "安全加密/",
      link: "安全加密/",
      collapsible: true,
      children: "structure",
    },
  ],
});
